# Generated by Django 2.2.2 on 2019-06-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190616_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='everything',
            old_name='address',
            new_name='accident_type',
        ),
        migrations.RenameField(
            model_name='everything',
            old_name='claims_during_fixes',
            new_name='planned_length',
        ),
        migrations.RenameField(
            model_name='everything',
            old_name='final_claims_after_fix',
            new_name='shift_days',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='comment_date',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='contract_ID',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='damage_rating',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='fix_date',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='fixed_too_late',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='reaction_speed_rating',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='real_end_date',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='real_start_date',
        ),
        migrations.RemoveField(
            model_name='everything',
            name='status_name',
        ),
        migrations.AddField(
            model_name='everything',
            name='accident_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='everything',
            name='shift_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
